CREATE SCHEMA Cars;
USE Cars;
SELECT * FROM car_dekho;
SELECT COUNT(*) FROM car_dekho;
SELECT COUNT(*) FROM car_dekho WHERE YEAR = 2023; #6
SELECT COUNT(*) FROM car_dekho WHERE YEAR = 2020; #74
SELECT COUNT(*) FROM car_dekho WHERE YEAR = 2021; #7
SELECT COUNT(*) FROM car_dekho WHERE YEAR = 2022; #7
SELECT COUNT(*) FROM car_dekho WHERE YEAR IN (2020,2021,2022,2023) GROUP BY YEAR ORDER BY YEAR  ASC;
SELECT YEAR, COUNT(*) FROM car_dekho GROUP BY YEAR ORDER BY YEAR  ASC;
SELECT COUNT(*) FROM car_dekho WHERE YEAR = 2020 AND FUEL = "DIESEL";
SELECT COUNT(*) FROM car_dekho WHERE YEAR = 2020 AND FUEL = "PETROL";
SELECT YEAR, COUNT(*) FROM car_dekho WHERE FUEL = "PETROL" GROUP BY YEAR ORDER BY YEAR  ASC; 
SELECT YEAR, COUNT(*) FROM car_dekho WHERE FUEL = "DIESEL" GROUP BY YEAR ORDER BY YEAR  ASC; 
SELECT YEAR, COUNT(*) FROM car_dekho WHERE FUEL = "CNG" GROUP BY YEAR ORDER BY YEAR  ASC; 
SELECT YEAR, COUNT(*) FROM car_dekho GROUP BY YEAR HAVING COUNT(*)>100; 
SELECT YEAR, COUNT(*) FROM car_dekho GROUP BY YEAR HAVING COUNT(*)<50; 
SELECT COUNT(*) FROM car_dekho WHERE YEAR BETWEEN 2015 AND 2023; 
SELECT * FROM car_dekho WHERE YEAR BETWEEN 2015 AND 2023 ORDER BY YEAR ASC;


